sudo: required
language: cpp
services:
- docker
before_install:
- docker build -t demoinfogo .
- mkdir artifacts
- docker run -v ${PWD}/artifacts:/demoinfogo/build -ti demoinfogo ./docker.sh
script:
- ls artifacts/demoinfogo
- cd artifacts && zip -r demoinfogo-linux.zip demoinfogo libs/
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "c7vbin6cskyQRPUCpfWOvNxuNdbbcZrpS/fXJabee9VCR4fXsT3/WtrW8wBj9z/Vs6oLTwGTb1WoOkRKzVTOQQxGjmlC2p3+TL3ASRkkeHwufnjR5hC+z8fAG56Cs8MXda66c4UoGusO5W9vD6mrBygBgKeRptdpf7ylvXqCGx6tPtARWawyj8TUt/vXQa++hegvtrXtVyQAJJNgI8Pu4Oz+/Ka0JWAArzhw4ey7v98CQ+fuaXGjrYyEllHau/Pe/r5MdmibgNQxM1c0RK0c0SOglWTxdGFTyI7SJqy42rFjMnoD1wvXAGFqwOSPl2ldCs3RJLxv2CrzIAsklAJlTCH/8ZopmaOcc7SUIxvdQnWWWpEIxjmckZgigKSuP7TEzVhHAkCu0VBsnLrpEGqdSCSc9F/CR5nM0UdGZXfeIug7ngzbnWv9hHlHXZKLG6wH2Tm6QRPan/NIIM9tA/mi5nuz+LtIqUZbuQXXBVGqT97xgvhvAWQO/lb+7aDoKyF30jUAk8uvCWfuCWH6v+qIxIlRYXzYmfz5PCduwbsbAOQFKOoqXRBxvIr7kxrhj6uhsUv/QAD0oggwSoJtgG9fSwOromHUK6xTJa376TExaUrnF+asIK+6W1wzIJGsVfsJCunXRzBrhxbd2AMVlxkcz6zX0FD4kpSkz2sn8b+Rrc8="

  file: demoinfogo-linux.zip
  draft: true
  on:
    repo: bugdone/demoinfogo-linux
    tags: true
